# Directories - CTP Dotfiles
DIR_CTP_DOTFILES=$(cd ../dotfiles && pwd)                      # Directory CTP: dotfiles/
DIR_CTP_CONKYRC="$DIR_CTP_DOTFILES/conky/.conkyrc"             # Directory CTP: .conkyrc
DIR_CTP_GITCONFIG="$DIR_CTP_DOTFILES/git/.gitconfig"           # Directory CTP: .gitconfig
DIR_CTP_MPD="$DIR_CTP_DOTFILES/mpd/.mpd"                       # Directory CTP: .mpd
DIR_CTP_NCMPCPP="$DIR_CTP_DOTFILES/ncmpcpp/.ncmpcpp"           # Directory CTP: .ncmpcpp
DIR_CTP_NEWSBEUTER="$DIR_CTP_DOTFILES/newsbeuter/.newsbeuter"  # Directory CTP: .newsbeuter
DIR_CTP_RTORRENTRC="$DIR_CTP_DOTFILES/rtorrent/.rtorrent.rc"   # Directory CTP: .rtorrent.rc
DIR_CTP_TMUXCONF="$DIR_CTP_DOTFILES/tmux/.tmux.conf"           # Directory CTP: .tmux.conf
DIR_CTP_VIMRC="$DIR_CTP_DOTFILES/vim/.vimrc"                   # Directory CTP: .vimrc
DIR_CTP_XINITRC="$DIR_CTP_DOTFILES/xinit/.xinitrc"             # Directory CTP: .xinitrc
DIR_CTP_XMONAD="$DIR_CTP_DOTFILES/xmonad/.xmonad"              # Directory CTP: .xmonad
DIR_CTP_XRESOURCES="$DIR_CTP_DOTFILES/xresources/.Xresources"  # Directory CTP: Xresources
DIR_CTP_ZSHRC="$DIR_CTP_DOTFILES/zsh/.zshrc"                   # Directory CTP: .zshrc

# Directories - Dotfiles
DIR_CONKYRC="$HOME/.conkyrc"                                   # Directory Conky: .conkyrc
DIR_GITCONFIG="$HOME/.gitconfig"                               # Directory Git: .gitconfig
DIR_MPD="$HOME/.mpd"                                           # Directory MPD: .mpd
DIR_MPDCONF="$HOME/.mpd/mpd.conf"                              # Directory MPD: mpd.conf
DIR_MPD_DB="$HOME/.mpd/db"                                     # Directory MPD: db
DIR_MPD_LOG="$HOME/.mpd/log"                                   # Directory MPD: log
DIR_MPD_PID="$HOME/.mpd/pid"                                   # Directory MPD: pid
DIR_MPD_PLAYLISTS="$HOME/Music/playlists"                      # Directory MPD: playlists
DIR_MPD_STATE="$HOME/.mpd/state"                               # Directory MPD: state
DIR_NCMPCPP="$HOME/.ncmpcpp"                                   # Directory ncmpcpp: .ncmpcpp
DIR_NEWSBEUTER="$HOME/.newsbeuter"                             # Directory Newsbeuter: .newsbeuter
DIR_RTORRENTRC="$HOME/.rtorrent.rc"                            # Directory rTorrent: .rtorrent.rc
DIR_RTORRENT_DOWNLOADS="$HOME/.rtorrent/downloads"             # Directory rTorrent: Downloads directory
DIR_RTORRENT_HOMEDL="$HOME/Downloads"                          # Directory rTorrent: HOME/Downloads directory
DIR_RTORRENT_MAIN="$HOME/.rtorrent"                            # Directory rTorrent: Main directory
DIR_RTORRENT_SESSION="$HOME/.rtorrent/session"                 # Directory rTorrent: Session directory
DIR_RTORRENT_TORRENTS="$HOME/.rtorrent/torrents"               # Directory rTorrent: Torrents directory
DIR_SH_BASH="/bin/bash"                                        # Directory Shell: Bash
DIR_SH_ZSH1="/bin/zsh"                                         # Directory Shell: Option 1
DIR_SH_ZSH2="/usr/bin/zsh"                                     # Directory Shell: Option 2
DIR_TMUXCONF="$HOME/.tmux.conf"                                # Directory tmux: .tmux.conf
DIR_VIMRC="$HOME/.vimrc"                                       # Directory vim: .vimrc
DIR_VIM_BUNDLE="$HOME/.vim/bundle"                             # Directory vim: Bundle directory
DIR_VIM_MAIN="$HOME/.vim"                                      # Directory vim: Main directory
DIR_VIM_SPELL="$HOME/.vim/spell"                               # Directory vim: Spell directory
DIR_XINITRC="$HOME/.xinitrc"                                   # Directory xinit: .xinitrc
DIR_XMONAD="$HOME/.xmonad"                                     # Directory xmonad: Main directory
DIR_XMONADHS="$HOME/.xmonad/xmonad.hs"                         # Directory xmonad: xmonad.hs 
DIR_XRESOURCES="$HOME/.Xresources"                             # Directory Xresources: .Xresources
DIR_ZSHRC="$HOME/.zshrc"                                       # Directory Zsh: .zshrc
